// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syrndqlynhogyahhjzej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5cm5kcWx5bmhvZ3lhaGhqemVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTIzMzQsImV4cCI6MjA3Mzg2ODMzNH0.M8JHdN8-Cq2HW-m49MkdCZ9LKuwSncm7IWZjLBngYqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});